#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "$0")/.." && pwd)"
compose_file="$repo_dir/docker-compose.yml"
dockerfile="$repo_dir/Dockerfile"
run_override="$repo_dir/container_overrides/run.sh"

grep -Fq 'pip3 install pyotp ib_insync --break-system-packages' "$dockerfile"
grep -Fq 'FROM gnzsnz/ib-gateway:10.37.1q' "$dockerfile"
grep -Fq 'LoginDialogDisplayTimeout=180' "$dockerfile"
grep -Fq 'failed to set LoginDialogDisplayTimeout' "$dockerfile"
grep -Fq '/home/ibgateway/ibc/config.ini.tmpl' "$dockerfile"
grep -Fq 'COPY --chown=1000:1000 ./container_overrides/run.sh /home/ibgateway/scripts/run.sh' "$dockerfile"
grep -Fq 'chmod a+x /home/ibgateway/scripts/run.sh' "$dockerfile"
grep -Fq 'libgtk-3-0' "$dockerfile"
grep -Fq 'libglib2.0-0' "$dockerfile"
grep -Fq 'libxtst6' "$dockerfile"
grep -Fq 'Xvfb "$DISPLAY" -ac -screen 0 "${IB_XVFB_SCREEN:-1024x768x24}" &' "$run_override"
grep -Fq -- '-ncache_cr -noxdamage' "$run_override"
grep -Fq 'configure_ibc_login_dialog_timeout' "$run_override"
grep -Fq 'IBC_LOGIN_DIALOG_DISPLAY_TIMEOUT:-180' "$run_override"
grep -Fq 'LoginDialogDisplayTimeout=${timeout}' "$run_override"
grep -Fq 'configure_ib_gateway_vmoptions' "$run_override"
grep -Fq 'find "${TWS_PATH}" -maxdepth 3 -name ibgateway.vmoptions' "$run_override"
grep -Fq 'IB_GATEWAY_PARALLEL_GC_THREADS:-2' "$run_override"
grep -Fq 'IB_GATEWAY_CONC_GC_THREADS:-1' "$run_override"
grep -Fq 'Java GC threads set to ParallelGCThreads=${parallel_threads}, ConcGCThreads=${conc_threads}' "$run_override"

grep -Fq '      - "4001:4003"' "$compose_file"
grep -Fq '      - "4002:4004"' "$compose_file"
grep -Fq '      - TWS_ACCEPT_INCOMING=${TWS_ACCEPT_INCOMING:-accept}' "$compose_file"
grep -Fq '      - READ_ONLY_API=${READ_ONLY_API:-no}' "$compose_file"
grep -Fq '      - TWOFA_DEVICE=${TWOFA_DEVICE:-}' "$compose_file"
grep -Fq '      - TWOFA_TIMEOUT_ACTION=${TWOFA_TIMEOUT_ACTION:-restart}' "$compose_file"
grep -Fq '      - RELOGIN_AFTER_TWOFA_TIMEOUT=${RELOGIN_AFTER_TWOFA_TIMEOUT:-yes}' "$compose_file"
grep -Fq '      - EXISTING_SESSION_DETECTED_ACTION=${EXISTING_SESSION_DETECTED_ACTION:-primary}' "$compose_file"
grep -Fq '      - IBKR_2FA_AUTOFILL=${IBKR_2FA_AUTOFILL:-yes}' "$compose_file"
grep -Fq '      - IBKR_2FA_MAX_SUBMISSIONS=${IBKR_2FA_MAX_SUBMISSIONS:-1}' "$compose_file"
grep -Fq '      - JAVA_HEAP_SIZE=${JAVA_HEAP_SIZE:-512}' "$compose_file"
grep -Fq '      - IB_GATEWAY_PARALLEL_GC_THREADS=${IB_GATEWAY_PARALLEL_GC_THREADS:-2}' "$compose_file"
grep -Fq '      - IB_GATEWAY_CONC_GC_THREADS=${IB_GATEWAY_CONC_GC_THREADS:-1}' "$compose_file"
grep -Fq '      - ACCEPT_API_FROM_IP=${ACCEPT_API_FROM_IP:?Set ACCEPT_API_FROM_IP to your Cloud Run egress subnet or connector CIDR}' "$compose_file"
