#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "$0")/.." && pwd)"
recover_script="$repo_dir/scripts/recover_ib_gateway_ready.sh"
swap_script="$repo_dir/scripts/ensure_host_swap.sh"
daily_restart_script="$repo_dir/scripts/restart_ib_gateway_daily.sh"
health_watcher_script="$repo_dir/scripts/install_gateway_health_watcher.sh"

test -f "$recover_script"
test -f "$swap_script"
test -f "$daily_restart_script"
test -f "$health_watcher_script"
test -x "$recover_script"
test -x "$swap_script"
test -x "$daily_restart_script"
test -x "$health_watcher_script"

grep -Fq 'IB_GATEWAY_RECOVERY_INITIAL_WAIT_SECONDS:-240' "$recover_script"
grep -Fq 'IB_GATEWAY_RECOVERY_RESTART_WAIT_SECONDS:-300' "$recover_script"
grep -Fq 'IB_GATEWAY_RECOVERY_RECREATE_WAIT_SECONDS:-360' "$recover_script"
grep -Fq 'IB_GATEWAY_RECOVERY_LOCK_FILE:-/var/lock/ib_gateway_recovery.lock' "$recover_script"
grep -Fq 'IB_GATEWAY_RECOVERY_LOCK_WAIT_SECONDS:-900' "$recover_script"
grep -Fq 'flock -n 9' "$recover_script"
grep -Fq 'flock -w "${lock_wait_seconds}" 9' "$recover_script"
grep -Fq 'docker compose restart "${container_name}"' "$recover_script"
grep -Fq 'docker compose up -d --force-recreate --no-build "${container_name}"' "$recover_script"
grep -Fq 'IB_GATEWAY_READY_TIMEOUT_SECONDS="${timeout_seconds}"' "$recover_script"

grep -Fq 'swap_size_mib="${IB_GATEWAY_SWAP_SIZE_MIB:-2048}"' "$swap_script"
grep -Fq 'fallocate -l "${swap_size_mib}M" "${swap_file}"' "$swap_script"
grep -Fq 'swapon "${swap_file}"' "$swap_script"
grep -Fq 'grep -Fq "${swap_file} none swap sw 0 0" /etc/fstab' "$swap_script"
grep -Fq 'printf '\''%s none swap sw 0 0\n'\'' "${swap_file}" >>/etc/fstab' "$swap_script"

grep -Fq 'docker compose restart "${container_name}"' "$daily_restart_script"
grep -Fq 'recover_ib_gateway_ready.sh" "${gateway_mode}"' "$daily_restart_script"

grep -Fq 'ibkr-gateway-healthcheck.service' "$health_watcher_script"
grep -Fq 'ibkr-gateway-healthcheck.timer' "$health_watcher_script"
grep -Fq 'ibkr-gateway-daily-restart.service' "$health_watcher_script"
grep -Fq 'ibkr-gateway-daily-restart.timer' "$health_watcher_script"
grep -Fq 'IB_GATEWAY_HEALTHCHECK_INTERVAL_SECONDS:-300' "$health_watcher_script"
grep -Fq 'IB_GATEWAY_DAILY_RESTART_ON_CALENDAR:-*-*-* 10:30:00 UTC' "$health_watcher_script"
grep -Fq 'Environment=IB_GATEWAY_RECOVERY_LOCK_WAIT_SECONDS=0' "$health_watcher_script"
grep -Fq 'enable --now ibkr-gateway-healthcheck.timer' "$health_watcher_script"
grep -Fq 'enable --now ibkr-gateway-daily-restart.timer' "$health_watcher_script"
! grep -Fq 'start ibkr-gateway-healthcheck.service' "$health_watcher_script"
