#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "$0")/.." && pwd)"
recover_script="$repo_dir/scripts/recover_ib_gateway_ready.sh"
classifier_script="$repo_dir/scripts/gateway_recovery_classifier.py"
classifier_wrapper="$repo_dir/scripts/classify_gateway_recovery_snapshot.sh"
ci_workflow="$repo_dir/.github/workflows/ci.yml"
swap_script="$repo_dir/scripts/ensure_host_swap.sh"
daily_restart_script="$repo_dir/scripts/restart_ib_gateway_daily.sh"
health_watcher_script="$repo_dir/scripts/install_gateway_health_watcher.sh"
unit_helper_script="$repo_dir/scripts/ibkr_gateway_units.sh"

test -f "$recover_script"
test -f "$classifier_script"
test -x "$classifier_wrapper"
test -f "$swap_script"
test -f "$daily_restart_script"
test -f "$health_watcher_script"
test -f "$unit_helper_script"
test -x "$recover_script"
test -x "$swap_script"
test -x "$daily_restart_script"
test -x "$health_watcher_script"
test -x "$unit_helper_script"

grep -Fq 'IB_GATEWAY_RECOVERY_INITIAL_WAIT_SECONDS:-240' "$recover_script"
grep -Fq 'IB_GATEWAY_RECOVERY_RESTART_WAIT_SECONDS:-300' "$recover_script"
grep -Fq 'IB_GATEWAY_RECOVERY_RECREATE_WAIT_SECONDS:-600' "$recover_script"
grep -Fq 'IB_GATEWAY_RECOVERY_PROGRESS_WAIT_SECONDS:-420' "$recover_script"
grep -Fq 'IB_GATEWAY_RECOVERY_PROGRESS_EXTENSIONS:-2' "$recover_script"
grep -Fq 'capture_epoch_decision()' "$recover_script"
grep -Fq 'classify_gateway_recovery_snapshot.sh' "$recover_script"
grep -Fq 'Python recovery classifier invocation failed' "$recover_script"
grep -Fq 'Immutable recovery snapshot shows login/config progress after ${stage} wait;' "$recover_script"
grep -Fq 'Freeze the bounded primitive event snapshot once for this attempt' "$recover_script"
grep -Fq "docker logs --timestamps --since \"\${epoch_started_at}\" \"\${epoch_container_id}\"" "$recover_script"
grep -Fq "docker exec \"\${epoch_container_id}\"" "$recover_script"
grep -Fq "[ -e \"\${log_path}\" ] && [ ! -f \"\${log_path}\" ]" "$recover_script"
grep -Fq "printf 'X\\tfile\\n'" "$recover_script"
expected_old_container_lookup='old_container_id="$(docker inspect --format '\''{{.Id}}'\'' "${container_name}"'
grep -Fq "$expected_old_container_lookup" "$recover_script"
grep -Fq "[ \"\${epoch_container_id}\" = \"\${old_container_id}\" ]" "$recover_script"
if grep -Fq 'IB_GATEWAY_RECOVERY_PROGRESS_WINDOW_SECONDS' "$recover_script" \
  || grep -Fq 'awk ' "$recover_script" \
  || grep -Fq 'Dismissing post-login dialog' "$recover_script"; then
  exit 1
fi
grep -Fq '/home/ibgateway/Jts/launcher.log' "$recover_script"
grep -Fq '/home/ibgateway/2fa.log' "$recover_script"
grep -Fq 'wait_for_ready_with_progress()' "$recover_script"
grep -Fq 'IB_GATEWAY_RECOVERY_LOCK_FILE:-/var/lock/ib_gateway_recovery.lock' "$recover_script"
grep -Fq 'IB_GATEWAY_RECOVERY_LOCK_WAIT_SECONDS:-900' "$recover_script"
grep -Fq 'flock -n 9' "$recover_script"
grep -Fq 'flock -w "${lock_wait_seconds}" 9' "$recover_script"
grep -Fq 'compose_service_name="${IB_GATEWAY_COMPOSE_SERVICE_NAME:-ib-gateway}"' "$recover_script"
grep -Fq 'docker compose restart "${compose_service_name}"' "$recover_script"
grep -Fq 'docker compose up -d --force-recreate --no-build "${compose_service_name}"' "$recover_script"
grep -Fq 'IB_GATEWAY_READY_TIMEOUT_SECONDS="${timeout_seconds}"' "$recover_script"
grep -Fq 'CONTAINER_NAME="${epoch_container_id}" bash "${script_dir}/ensure_2fa_bot_running.sh"' "$recover_script"
ensure_count="$(grep -c 'ensure_2fa_bot_running' "$recover_script")"
test "$ensure_count" -ge 4

grep -Fq 'bash tests/test_gateway_recovery_scripts.sh' "$ci_workflow"
grep -Fq 'bash tests/test_gateway_recovery_classifier_invocation.sh' "$ci_workflow"
grep -Fq 'python3 tests/test_gateway_recovery_classifier.py' "$ci_workflow"

grep -Fq 'swap_size_mib="${IB_GATEWAY_SWAP_SIZE_MIB:-2048}"' "$swap_script"
grep -Fq 'fallocate -l "${swap_size_mib}M" "${swap_file}"' "$swap_script"
grep -Fq 'swapon "${swap_file}"' "$swap_script"
grep -Fq 'grep -Fq "${swap_file} none swap sw 0 0" /etc/fstab' "$swap_script"
grep -Fq 'printf '\''%s none swap sw 0 0\n'\'' "${swap_file}" >>/etc/fstab' "$swap_script"

grep -Fq 'compose_service_name="${IB_GATEWAY_COMPOSE_SERVICE_NAME:-ib-gateway}"' "$daily_restart_script"
grep -Fq 'docker compose restart "${compose_service_name}"' "$daily_restart_script"
grep -Fq 'recover_ib_gateway_ready.sh" "${gateway_mode}"' "$daily_restart_script"

grep -Fq 'resolve_ibkr_gateway_unit_names "$container_name" "$unit_suffix"' "$health_watcher_script"
grep -Fq '$IBKR_GATEWAY_HEALTHCHECK_SERVICE' "$health_watcher_script"
grep -Fq '$IBKR_GATEWAY_HEALTHCHECK_TIMER' "$health_watcher_script"
grep -Fq '$IBKR_GATEWAY_DAILY_RESTART_SERVICE' "$health_watcher_script"
grep -Fq '$IBKR_GATEWAY_DAILY_RESTART_TIMER' "$health_watcher_script"
grep -Fq 'IB_GATEWAY_HEALTHCHECK_INTERVAL_SECONDS:-300' "$health_watcher_script"
grep -Fq 'IB_GATEWAY_DAILY_RESTART_ON_CALENDAR:-*-*-* 10:30:00 UTC' "$health_watcher_script"
grep -Fq 'compose_service_name="${IB_GATEWAY_COMPOSE_SERVICE_NAME:-ib-gateway}"' "$health_watcher_script"
grep -Fq 'gateway_mode="${1:-${IB_GATEWAY_MODE:-paper}}"' "$health_watcher_script"
grep -Fq 'compose_file="${COMPOSE_FILE:-docker-compose.yml}"' "$health_watcher_script"
grep -Fq 'Environment=IB_GATEWAY_COMPOSE_SERVICE_NAME=$compose_service_name' "$health_watcher_script"
grep -Fq 'Environment=COMPOSE_FILE=$compose_file' "$health_watcher_script"
grep -Fq 'Environment=IB_GATEWAY_RECOVERY_LOCK_FILE=$recovery_lock_file' "$health_watcher_script"
grep -Fq 'Environment=IB_GATEWAY_RECOVERY_LOCK_WAIT_SECONDS=0' "$health_watcher_script"
grep -Fq 'OnActiveSec=$health_interval_seconds' "$health_watcher_script"
grep -Fq 'Persistent=false' "$health_watcher_script"
! grep -Fq 'OnBootSec=5min' "$health_watcher_script"
grep -Fq 'enable --now "$IBKR_GATEWAY_HEALTHCHECK_TIMER"' "$health_watcher_script"
grep -Fq 'enable --now "$IBKR_GATEWAY_DAILY_RESTART_TIMER"' "$health_watcher_script"
! grep -Fq 'start ibkr-gateway-healthcheck.service' "$health_watcher_script"

grep -Fq 'resolve_ibkr_gateway_unit_suffix()' "$unit_helper_script"
grep -Fq 'IBKR_2FA_BOT_SERVICE="ibkr-2fa-bot${unit_infix}.service"' "$unit_helper_script"
